cookie:
  expiry_days: 7
  key: 5RkjSzB6w0edJLxUZlwQTXljuPwOvh8ncIkjLsIHY1tKr_KokmdjAVXg4iLqhhZAu7zz75V6pnXC23IoUGIAPg
  name: streamlit_auth_cookie
credentials:
  usernames:
    admin:
      email: thibaut.nguyen@spallian.com
      name: Administrateur
      password: $2b$14$JkDHb1vtxRFPgqRUbSoudeIJYDGbva8rB38BnIrhJMThAYT4cOe2C
preauthorized:
  emails:
  - thibaut.nguyen@spallian.com
