# Clé API pour neon.tech
NEON_API_KEY = "napi_40g81dc3l11a08wos2rt63q2im3qnz9cnykro6wc3mohivxf3jtzz0o4wfbbnnqu"

# URL de l'API neone.tech
NEON_API_URL = "https://console.neon.tech/api/v2/"

# Configuration de la base de données Neon.tech
NEON_HOST = "ep-wispy-queen-abzi1lne-pooler.eu-west-2.aws.neon.tech"
NEON_DATABASE = "neondb"
NEON_USER = "neondb_owner"
NEON_PASSWORD = "npg_XsA4wfvHy2Rn" 